<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Services\ContractRoom\Queries\" />
    <Folder Include="Services\Contracts\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BTravel.CommonDefinitions\BTravel.CommonDefinitions.csproj" />
    <ProjectReference Include="..\BTravel.DAL\BTravel.DAL.csproj" />
  </ItemGroup>

</Project>
